use std::path::PathBuf;

use clap::{Args, Parser, Subcommand, ValueEnum};

#[derive(Parser)]
#[command(
    name = "sg-packager",
    about = "Builds signed Survival Realms .sg packages"
)]
pub(crate) struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand)]
pub(crate) enum Command {
    /// Generates a new private/public Ed25519 signing-key pair.
    Keygen(KeygenArgs),
    /// Compiles and packages a Survival Realms version.
    Build(BuildArgs),
    /// Builds a signed repository index from the packaged versions.
    Index(IndexArgs),
}

#[derive(Args)]
pub(crate) struct IndexArgs {
    /// Private signing key used for the .sg packages and repository index.
    #[arg(long, env = "SG_SIGNING_KEY_FILE")]
    pub key: PathBuf,
    /// Public HTTPS directory containing the .sg files.
    #[arg(long, env = "SG_REPOSITORY_BASE_URL")]
    pub base_url: String,
    /// Directory containing .sg files. Defaults to <workspace>/versions.
    #[arg(long)]
    pub versions_dir: Option<PathBuf>,
    /// Signed index destination. Defaults to <versions-dir>/index.json.
    #[arg(long)]
    pub output: Option<PathBuf>,
    /// Public asset directory included in the signed index. Defaults to <workspace>/assets.
    #[arg(long)]
    pub assets_dir: Option<PathBuf>,
    /// Asset-pack id. Defaults to the single id referenced by all indexed versions.
    #[arg(long)]
    pub asset_pack_id: Option<String>,
}

#[derive(Args)]
pub(crate) struct KeygenArgs {
    /// Destination for the private key. A matching .pub file is also created.
    #[arg(long)]
    pub output: PathBuf,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
pub(crate) enum ChannelArgument {
    Development,
    Snapshot,
    Release,
}

impl ChannelArgument {
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::Development => "development",
            Self::Snapshot => "snapshot",
            Self::Release => "release",
        }
    }
}

#[derive(Args)]
pub(crate) struct BuildArgs {
    /// Private signing key generated by `sg-packager keygen`.
    #[arg(long, env = "SG_SIGNING_KEY_FILE")]
    pub key: PathBuf,
    /// Output .sg path. Defaults to versions/<game-version>.sg.
    #[arg(long)]
    pub output: Option<PathBuf>,
    /// Asset-pack identifier embedded into the game and package.
    #[arg(long)]
    pub asset_pack: Option<String>,
    /// Release channel embedded into the build.
    #[arg(long, value_enum, default_value = "release")]
    pub channel: ChannelArgument,
    /// Skip Cargo compilation and use the existing distribution executable.
    #[arg(long)]
    pub skip_compile: bool,
    /// Zstandard compression level.
    #[arg(long, default_value_t = 19, value_parser = clap::value_parser!(i32).range(1..=22))]
    pub compression_level: i32,
    /// Maximum parallel Rust compiler processes used for the hardened build.
    #[arg(long, default_value_t = 2, value_parser = clap::value_parser!(u16).range(1..=64))]
    pub jobs: u16,
}
